name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Set up environment variables
        run: |
          echo TYPE=${{ secrets.TYPE }} >> $GITHUB_ENV
          echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> $GITHUB_ENV
          echo PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }} >> $GITHUB_ENV
          echo PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
          echo CLIENT_EMAIL=${{ secrets.CLIENT_EMAIL }} >> $GITHUB_ENV
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> $GITHUB_ENV
          echo AUTH_URI=${{ secrets.AUTH_URI }} >> $GITHUB_ENV
          echo TOKEN_URI=${{ secrets.TOKEN_URI }} >> $GITHUB_ENV
          echo AUTH_PROVIDER_X509_CERT_URL=${{ secrets.AUTH_PROVIDER_X509_CERT_URL }} >> $GITHUB_ENV
          echo CLIENT_X509_CERT_URL=${{ secrets.CLIENT_X509_CERT_URL }} >> $GITHUB_ENV
          echo R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }} >> $GITHUB_ENV
          echo R2_SECRET_KEY=${{ secrets.R2_SECRET_KEY }} >> $GITHUB_ENV
          echo R2_API_TOKEN=${{ secrets.R2_API_TOKEN }} >> $GITHUB_ENV
